### ISSUE TITLE
Article decoding error

### ISSUE THREAD

**Issue by AureliusWasRight** [latin-dict/Gesner1749#1]
Hello, I've been experiencing an issue regarding the decoding of my queries. No matter what I search for, the message that comes up is always "Article decoding error"

![image](https://user-images.githubusercontent.com/92296215/150878213-5f5c1e38-c182-431a-b07a-9e7eab495896.png)

The search function works correctly, as it is displaying possible options as below:

![image](https://user-images.githubusercontent.com/92296215/150878319-51ea8d5f-c660-4d1c-9150-73315a00ff75.png)

The current version of GoldenDict is as follows:

![image](https://user-images.githubusercontent.com/92296215/150878376-055ab1ab-77f3-4ccc-bffb-d8d98d47b4ab.png)

I downloaded the dictionary from your github repo as here:

![image](https://user-images.githubusercontent.com/92296215/150879032-bb7a55d4-fc2e-49f4-8016-9435054cb733.png)

And the GoldenDict through the repo of early acces builds your page links to:

![image](https://user-images.githubusercontent.com/92296215/150879184-90cb5ff9-bfd7-4f19-8ff8-ca6b86712248.png)

I reinstalled the app aswell as the dictionary, yet to no avail.
I'd really appreacite some help regarding this. If you need more info, don't hesitate to ask.

**Comment by nikita-moor** [comment]
The message "Article decoding error" usually means an outdated version of GoldenDict, but you say using an early access builds… I have no ideas. Try [xiaoyifang's releases](https://github.com/xiaoyifang/goldendict/releases) ([GoldenDict-staged.71f26b2-050518.zip](https://github.com/xiaoyifang/goldendict/releases/download/pre-20220205-staged/GoldenDict-staged.71f26b2-050518.zip)). His version had a problem with opening full-size images though, but I can't check it now.

**Comment by AureliusWasRight** [comment]
Thank you so much for the suggestion!
After I downloaded xiayifang's release it works flawlessly! :)

![image](https://user-images.githubusercontent.com/92296215/152700754-22ea0c9a-97d4-4c16-9d56-545c3f9b54f9.png)
